<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;Test</Configurations>
        <PackageId>CPIT.$(AssemblyName)</PackageId>
        <Authors>CPIT</Authors>
        <Description>Manage users .Net library</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Version>2.1.0</Version>
        <PackageVersion>4.4.0</PackageVersion>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="EmailTemplates\**" />
      <EmbeddedResource Remove="EmailTemplates\**" />
      <None Remove="EmailTemplates\**" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google.Apis.Auth" Version="1.70.0" />
      <PackageReference Include="Google.Apis.Drive.v3" Version="1.70.0.3856" />
      <PackageReference Include="Google.Cloud.SecretManager.V1" Version="2.6.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.19" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.19">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\README.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

</Project>
